'use client';

import React from 'react';
import { ShubhamLogo } from './ShubhamLogo';

interface ProductionSheetProps {
  program: any;
  currentChallan?: any;
  activeDepartment?: string;
  onClose?: () => void;
}

export function ProductionSheetTraveler({
  program,
  currentChallan,
  activeDepartment,
  onClose,
}: ProductionSheetProps) {
  if (!program) return null;

  const handlePrint = () => {
    window.print();
  };

  const fabrics = program.fabrics || [];
  const colours = program.colours || [];
  const sizes = program.sizes || [];
  const routes = program.routes?.[0]?.steps || [];

  return (
    <div className="bg-white text-slate-900 rounded-xl border border-slate-300 shadow-xl max-w-4xl w-full mx-auto p-6 sm:p-8 font-sans print:shadow-none print:border-none print:p-2">
      {/* Top Action Bar for Screen view */}
      <div className="flex items-center justify-between border-b border-slate-200 pb-3 mb-4 no-print">
        <div className="flex items-center gap-2">
          <span className="w-2.5 h-2.5 rounded-full bg-blue-600"></span>
          <span className="text-xs font-bold uppercase tracking-wider text-blue-900 font-mono">
            Official Manufacturing Traveler Sheet (Attached to Challan)
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-white rounded text-xs font-semibold flex items-center gap-1.5 shadow-xs transition"
          >
            <span>🖨️</span> Print Traveler
          </button>
          {onClose && (
            <button
              onClick={onClose}
              className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded text-xs font-semibold transition"
            >
              ✕ Close
            </button>
          )}
        </div>
      </div>

      {/* ======================================================== */}
      {/* TRAVELER DOCUMENT HEADER - Generated by Programming Dept */}
      {/* ======================================================== */}
      <div className="border-2 border-slate-900 p-4 rounded-lg bg-slate-50/50 mb-6">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 border-b-2 border-slate-900 pb-3">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-white rounded border border-slate-300 flex items-center justify-center p-1">
              <ShubhamLogo size="sm" showSubtitle={false} />
            </div>
            <div>
              <h1 className="text-base font-bold tracking-tight text-slate-900 uppercase">
                Shubham Fabrics India Pvt. Ltd.
              </h1>
              <p className="text-[11px] font-mono text-slate-600">
                MASTER PRODUCTION SHEET & SHOP-FLOOR TRAVELER
              </p>
              <span className="inline-block text-[9px] font-mono font-bold px-1.5 py-0.5 rounded bg-blue-100 text-blue-800 mt-0.5">
                GENERATED BY PROGRAMMING & PLANNING DEPARTMENT ONLY
              </span>
            </div>
          </div>

          <div className="text-right">
            <div className="text-sm font-mono font-black text-slate-900 border border-slate-800 px-3 py-1 rounded bg-white inline-block">
              {program.programNumber}
            </div>
            <p className="text-[10px] font-mono text-slate-500 mt-1">
              Date: {new Date(program.createdAt || Date.now()).toLocaleDateString()}
            </p>
          </div>
        </div>

        {/* Core Order Metadata Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-3 text-xs">
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-500 block">Buyer / Customer</span>
            <span className="font-semibold text-slate-900">{program.customer?.name || program.buyerName || 'Standard Client'}</span>
          </div>
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-500 block">Order Number</span>
            <span className="font-mono font-semibold text-slate-900">{program.orderNumber || 'ORD-2026-001'}</span>
          </div>
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-500 block">Design / Style Code</span>
            <span className="font-mono font-semibold text-slate-900">{program.styleCode || 'SF-3201'} ({program.designName})</span>
          </div>
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-500 block">Target Quantity</span>
            <span className="font-mono font-bold text-blue-800 text-sm">{program.targetQuantity?.toLocaleString()} PCS</span>
          </div>
        </div>
      </div>

      {/* ======================================================== */}
      {/* SIZE & COLOUR BREAKDOWN MATRIX */}
      {/* ======================================================== */}
      <div className="mb-6">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-2 flex items-center gap-1.5">
          <span>📐</span> Size & Colour Quantity Matrix
        </h2>
        <div className="border border-slate-300 rounded-lg overflow-hidden">
          <table className="w-full text-xs text-left">
            <thead className="bg-slate-100 border-b border-slate-300 text-slate-700 font-semibold">
              <tr>
                <th className="py-2 px-3">Colour / Shade</th>
                <th className="py-2 px-3">Color Code</th>
                <th className="py-2 px-3 text-right">Target Pcs</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {colours.length > 0 ? (
                colours.map((c: any, idx: number) => (
                  <tr key={idx} className="hover:bg-slate-50">
                    <td className="py-2 px-3 font-medium text-slate-900">{c.colorName}</td>
                    <td className="py-2 px-3 font-mono text-slate-600">{c.colorCode}</td>
                    <td className="py-2 px-3 font-mono font-bold text-right text-slate-900">
                      {c.targetQuantity?.toLocaleString() || '-'}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td className="py-2 px-3 font-medium text-slate-900">Navy Blue (Standard)</td>
                  <td className="py-2 px-3 font-mono text-slate-600">COL-NAVY-01</td>
                  <td className="py-2 px-3 font-mono font-bold text-right text-slate-900">
                    {program.targetQuantity?.toLocaleString() || '5,000'}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ======================================================== */}
      {/* BILL OF MATERIALS (FABRIC REQUIREMENTS) */}
      {/* ======================================================== */}
      <div className="mb-6">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-2 flex items-center gap-1.5">
          <span>🧵</span> Fabric Specifications (BOM)
        </h2>
        <div className="border border-slate-300 rounded-lg overflow-hidden">
          <table className="w-full text-xs text-left">
            <thead className="bg-slate-100 border-b border-slate-300 text-slate-700 font-semibold">
              <tr>
                <th className="py-2 px-3">Fabric Code</th>
                <th className="py-2 px-3">Composition</th>
                <th className="py-2 px-3">GSM</th>
                <th className="py-2 px-3">Width</th>
                <th className="py-2 px-3 text-right">Required (KG)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {fabrics.length > 0 ? (
                fabrics.map((f: any, idx: number) => (
                  <tr key={idx}>
                    <td className="py-2 px-3 font-mono font-semibold text-slate-900">{f.fabricCode}</td>
                    <td className="py-2 px-3 text-slate-700">{f.composition || '100% Combed Cotton'}</td>
                    <td className="py-2 px-3 font-mono text-slate-700">{f.gsm || 180}</td>
                    <td className="py-2 px-3 font-mono text-slate-700">{f.widthInInches || 60}&quot;</td>
                    <td className="py-2 px-3 font-mono font-bold text-right text-slate-900">
                      {f.requiredQuantity?.toLocaleString() || '1,250'} KG
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td className="py-2 px-3 font-mono font-semibold text-slate-900">FAB-COT-180</td>
                  <td className="py-2 px-3 text-slate-700">100% Combed Cotton Single Jersey</td>
                  <td className="py-2 px-3 font-mono text-slate-700">180</td>
                  <td className="py-2 px-3 font-mono text-slate-700">60&quot;</td>
                  <td className="py-2 px-3 font-mono font-bold text-right text-slate-900">1,250 KG</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ======================================================== */}
      {/* CHAIN OF CUSTODY: ROUTE CHECKLIST PASSING WITH EACH CHALLAN */}
      {/* ======================================================== */}
      <div>
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 mb-2 flex items-center justify-between">
          <span className="flex items-center gap-1.5">
            <span>📋</span> Inter-Departmental Chain of Custody & Approvals
          </span>
          <span className="text-[10px] text-slate-500 font-normal">
            Must be signed and stamped at each sequential handoff
          </span>
        </h2>

        <div className="border border-slate-300 rounded-lg overflow-hidden">
          <table className="w-full text-xs text-left">
            <thead className="bg-slate-100 border-b border-slate-300 text-slate-700 font-semibold">
              <tr>
                <th className="py-2 px-3">Seq</th>
                <th className="py-2 px-3">Department</th>
                <th className="py-2 px-3">Challan Handoff</th>
                <th className="py-2 px-3">Output Qty</th>
                <th className="py-2 px-3">QA Gate</th>
                <th className="py-2 px-3">Status</th>
                <th className="py-2 px-3">Sign / Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {[
                { seq: 1, dept: 'STORE', name: 'Raw Material Store', challan: 'CHL-ST-001', qty: '1,250 KG', qa: 'Pass (Rolls)', status: 'COMPLETED', sign: 'M. Verma' },
                { seq: 2, dept: 'DYEING', name: 'Dyeing & Processing', challan: 'CHL-DY-001', qty: '1,210 KG', qa: 'QC-1 Passed', status: 'COMPLETED', sign: 'R. Sharma' },
                { seq: 3, dept: 'CUTTING', name: 'Cutting & Bundles', challan: 'CHL-CU-001', qty: '5,000 PCS', qa: 'Lay Audit Passed', status: 'COMPLETED', sign: 'A. Patel' },
                { seq: 4, dept: 'STITCHING', name: 'Garment Sewing Lines', challan: 'CHL-ST-002', qty: '5,000 PCS', qa: 'Inline Audit Pass', status: 'IN_PROGRESS', sign: 'S. Nair' },
                { seq: 5, dept: 'FINISHING', name: 'Finishing & Pressing', challan: 'CHL-FN-001', qty: '5,000 PCS', qa: '100% Audit', status: 'PENDING', sign: '—' },
                { seq: 6, dept: 'PACKING', name: 'Folding & Carton Packing', challan: 'CHL-PK-001', qty: '10 CTNS', qa: 'Carton Barcode', status: 'PENDING', sign: '—' },
                { seq: 7, dept: 'DISPATCH', name: 'Finished Goods Logistics', challan: 'DSP-2026-001', qty: '5,000 PCS', qa: 'LR Verified', status: 'PENDING', sign: '—' },
              ].map((step) => {
                const isCurrent = activeDepartment === step.dept;
                return (
                  <tr key={step.seq} className={isCurrent ? 'bg-blue-50/80 font-medium' : ''}>
                    <td className="py-2 px-3 font-mono text-slate-500">#{step.seq}</td>
                    <td className="py-2 px-3">
                      <span className="font-semibold text-slate-900 block">{step.dept}</span>
                      <span className="text-[10px] text-slate-500">{step.name}</span>
                    </td>
                    <td className="py-2 px-3 font-mono text-blue-700">{step.challan}</td>
                    <td className="py-2 px-3 font-mono font-medium text-slate-900">{step.qty}</td>
                    <td className="py-2 px-3 text-[11px] text-emerald-700 font-medium">{step.qa}</td>
                    <td className="py-2 px-3">
                      <span
                        className={`text-[10px] font-mono px-2 py-0.5 rounded font-semibold ${
                          step.status === 'COMPLETED'
                            ? 'bg-emerald-100 text-emerald-800'
                            : step.status === 'IN_PROGRESS'
                            ? 'bg-blue-100 text-blue-800 animate-pulse'
                            : 'bg-slate-100 text-slate-600'
                        }`}
                      >
                        {step.status}
                      </span>
                    </td>
                    <td className="py-2 px-3 font-mono text-[11px] text-slate-700">{step.sign}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Footer Instructions for Factory Operators */}
      <div className="mt-6 pt-4 border-t border-slate-300 text-[11px] text-slate-500 flex flex-col sm:flex-row items-center justify-between gap-2">
        <p>
          ⚠️ <strong>Mandatory Rule:</strong> This sheet must physically and digitally accompany every handoff challan. No department may accept material without scanning the matching production sheet.
        </p>
        <span className="font-mono text-[10px] text-slate-400 shrink-0">
          Doc ID: PS-{program.programNumber}-REV1
        </span>
      </div>
    </div>
  );
}
