FROM node:24-alpine AS base
WORKDIR /app
RUN npm install -g pnpm

FROM base AS builder
WORKDIR /app
COPY package*.json ./
COPY packages/ packages/
COPY apps/api/ apps/api/
RUN npm install
RUN npm run build --workspace=@subham/types
RUN npm run build --workspace=@subham/validation
RUN npm run build --workspace=@subham/config
RUN npm run generate --workspace=@subham/database
RUN npm run build --workspace=@subham/database
RUN npm run build --workspace=@subham/api

FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/packages/ packages/
COPY --from=builder /app/apps/api/ apps/api/
COPY --from=builder /app/node_modules/ node_modules/

EXPOSE 3001
CMD ["node", "apps/api/dist/main.js"]
