FROM node:24-alpine AS base
WORKDIR /app

FROM base AS builder
WORKDIR /app
COPY package*.json ./
COPY packages/ packages/
COPY apps/web/ apps/web/
RUN npm install
RUN npm run build --workspace=@subham/types
RUN npm run build --workspace=@subham/validation
RUN npm run build --workspace=@subham/config
RUN npm run build --workspace=@subham/web

FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/packages/ packages/
COPY --from=builder /app/apps/web/ apps/web/
COPY --from=builder /app/node_modules/ node_modules/

EXPOSE 3000
CMD ["npm", "run", "start", "--workspace=@subham/web"]
